### PR TITLE
Merge botbrains with main.

### PR DESCRIPTION
**Pull request by benmwilson**
Give life to ApostleAI on the main branch.

### CODE REVIEW

**Review by onlinestang — APPROVED** [review]
Let there be light!
Good work!

**Comment by benmwilson** [comment]
bapati boopati merge the branch ya see

**Comment by benmwilson** [comment]
[The big assignment 2 merge](https://trello.com/c/crDNa6WE/94-the-big-assignment-2-merge)

**Comment by benmwilson** [comment]
[The big assignment 2 merge](https://trello.com/c/crDNa6WE/94-the-big-assignment-2-merge)

**Pull request merged**
